### ISSUE TITLE
[DOCS] Expand details about Data Visualizer

### ISSUE THREAD

**Issue by elasticmachine** [elastic/stack-docs#566]
*Original comment by @lcawl:*

Per LINK REDACTED

"... if we want to fully document the functionality in the Data Visualizer, items that are not covered are:

- Use of the query bar to narrow the data being visualized
- Use of the filter boxes in the Metric and Fields section to filter the fields being displayed
- Use of the field types dropdown in the Fields section to view one field type at a time e.g. view only IP type fields
- Further discussion on the metric distribution chart - shows where the values in the data are clustered
- boolean field example
- IP field example
- geo_point field example
- text field example (up to 10 example values of this field are displayed)
- checkboxes for showing empty fields i.e. those which don't appear in any documents
- Caution when altering the 'sample' size field as it will lead to increased query run times and the load on the cluster
- If the fields match recognized configurations, links to the specialized wizards will appear on the right ..."

Some of this might be appropriate for help inside the UI, but it should be considered for inclusion in the Kibana User Guide > Machine Learning nonetheless.

**Comment by lcawl** [comment]
The Data Visualizer is discussed in the following section of the documentation: https://www.elastic.co/guide/en/machine-learning/master/ml-gs-visualizer.html

I have actually reduced the amount of screenshots (from previous incarnations of this tutorial), since it seemed more important to encourage trying out the tool rather than documenting all of its field-specific options.
